<a href="https://colab.research.google.com/github/Amlan05/Pytorch_learning/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3


**TENSORS**



*   A torch, Tensor is a multi-dimensional matrix containing elements in a single data type
*   Similar to numpy array, but full of fun things that make them work better in GPU's (vs regular CPU's)
*   Default datatype is float32
*   More suitable for deep learning than a numpy array





In [ ]:
# python list

my_list = [[1,1,2,3,5], [6,7,8,9,10]]
my_list

[[1, 1, 2, 3, 5], [6, 7, 8, 9, 10]]

In [ ]:
# numpy array

import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.7743482 , 0.71503145, 0.08231338, 0.18172574],
       [0.08178713, 0.12395031, 0.50469133, 0.31925521],
       [0.19473272, 0.15421288, 0.08121947, 0.82777225]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
# tensors
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0051, -2.2295, -0.3108,  0.7103],
        [ 1.2274,  0.5362, -0.5971, -1.4604],
        [ 2.0757, -0.5280, -0.3212, -1.0644]])

In [ ]:
 tensor_3d = torch.zeros(2,3,4)
 tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7743, 0.7150, 0.0823, 0.1817],
        [0.0818, 0.1240, 0.5047, 0.3193],
        [0.1947, 0.1542, 0.0812, 0.8278]], dtype=torch.float64)

In [ ]:
# tensor operation

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view

my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items using -1

my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_torch = my_torch2.reshape(3, -1)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# view
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# difference between shape and view

In [ ]:
# with reshape and view, they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
# slices -> grab of a section of the tensor

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# grab a specific term
my_torch7[7]

tensor(7)

In [ ]:
# grab slice

my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# return a column

my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**TENSOR MATH OPERATION**

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# substraction

tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [ ]:
# Sub Function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
# multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# Mul longhand

torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# division

tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# remainder longhand

torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# exponents / power

tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
# exponent longhand

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# another way to write longhand

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# tensor assignment
# tensor_a = tensor_a +  tensor_b
tensor_a.add_(tensor_b)

tensor([26, 32, 38, 44])